version: "3.7"

services:
  mongo:
    hostname: vahter_mongo
    container_name: vahter_mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo/data/db:/data/db
    command: "mongod --replSet rs0"
